### ISSUE TITLE
Add configuration for whitelisting endpoints.

### ISSUE THREAD

**Issue by mk23** [mk23/jmxproxy#14]
For example:

``` yaml
jmxproxy:
    allowed_endpoints:
        - "host1:port1"
        - "host1:port2"
        - "host2:port3"
```

If the list is missing or empty, allow all hosts.
